if(process.env.NODE_ENV=='production'){
module.exports={
    mongoURI:'mongodb+srv://sush:RockBottom@projecthubcluster-8oj2j.mongodb.net/projectHub-dev'
}
}
else{
    module.exports={
        mongoURI:'mongodb://localhost:27017/projectHub-dev'
    }
}